### PR TITLE
feat: support recursive dispatching async actions

### LINKED ISSUE #7: Async action calling another async action
1. React component dispatches async action
2. async action has some side effects, and dispatches another async action

Is it possible with this library, or will the async actions dispatched from within another async action be ignored?

### PR DESCRIPTION
**Pull request by dai-shi**
resolve #7

### CODE REVIEW

**Comment by dai-shi** [comment]
@gabrielhpugliese Hi, can you try the codesandbox build and confirm if it solves your use case?

**Comment by gabrielhpugliese** [comment]
Looks like it works! https://codesandbox.io/s/react-forked-gkxe2?file=/src/App.js
Thanks for considering it and implementing it 👍

**Comment by dai-shi** [comment]
Thanks for confirming.

This might cause inconvenience with typescript, but will see. Let's ship it.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-reducer-async/v/2.1.0

**Pull request merged**
